apiVersion: apps/v1
kind: Deployment
metadata:
  name: hsaab-flux-quantum-bank-backend-deployment
  namespace: hsaab-flux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hsaab-flux-quantum-bank-backend-deployment
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hsaab-flux-quantum-bank-backend-deployment
    spec:
      containers:
      - name: quantum-bank-backend
        # hsaab/quantum-bank-backend:140 for old
        image: hsaab/quantum-bank-backend:168
        imagePullPolicy: "Always"
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"